name: Daily Attendance

on:
  schedule:
    - cron: '30 5 * * 1-5'   # 11:00 AM IST
    - cron: '30 15 * * 1-5'  # 9:00 PM IST
  workflow_dispatch:

jobs:
  run-attendance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Install dependencies
      run: dotnet restore AttendanceBot

    - name: Install Chrome
      run: |
        sudo apt update
        sudo apt install -y wget unzip
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb

    - name: Remove old ChromeDriver
      run: sudo rm -f /usr/bin/chromedriver /usr/local/bin/chromedriver || true

    - name: Install matching ChromeDriver
      run: |
        # Get the installed Chrome major version (e.g., 130)
        CHROME_VERSION=$(google-chrome --version | grep -oE "[0-9.]+" | cut -d "." -f1)
        echo "Detected Chrome major version: $CHROME_VERSION"

        # Get the latest matching ChromeDriver version for this Chrome version
        DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
        echo "Matching ChromeDriver version: $DRIVER_VERSION"

        # Download and install the matching ChromeDriver
        wget -N "https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip"
        unzip -o chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Check Chrome version
      run: google-chrome --version

    - name: Check ChromeDriver version
      run: chromedriver --version

    - name: Run attendance script
      env:
        HONO_USERNAME: ${{ secrets.HONO_USERNAME }}
        HONO_PASSWORD: ${{ secrets.HONO_PASSWORD }}
      run: dotnet run --project AttendanceBot
