name: Daily Attendance

on:
  schedule:
    - cron: '10 4 * * *'   # 11:00 AM IST (UTC +5:30)
    - cron: '30 15 * * *'  # 9:00 PM IST (UTC +5:30)
  workflow_dispatch:

jobs:
  run-attendance:
    runs-on: ubuntu-latest

    steps:
    - name: Log current UTC and IST time
      run: |
        echo "⏰ Current UTC Time: $(date -u)"
        echo "⏰ Approx IST Time: $(TZ='Asia/Kolkata' date)"

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Install dependencies
      run: dotnet restore AttendanceBot

    - name: Install Chrome
      run: |
        sudo apt update
        sudo apt install -y wget unzip
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb

    - name: Run attendance script
      env:
        HONO_USERNAME: ${{ secrets.HONO_USERNAME }}
        HONO_PASSWORD: ${{ secrets.HONO_PASSWORD }}
      run: |
        echo "🚀 Running Attendance Script..."
        dotnet run --project AttendanceBot

    - name: Notify Success
      if: success()
      run: echo "✅ Attendance successfully marked."

    - name: Notify Failure
      if: failure()
      run: echo "❌ Attendance script failed. Check logs above."
