name: Daily Attendance

on:
  schedule:
    - cron: '30 5 * * 1-5'   # 11:00 AM IST
    - cron: '30 15 * * 1-5'  # 9:00 PM IST
  workflow_dispatch:

jobs:
  run-attendance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Install dependencies
      run: dotnet restore AttendanceBot

    - name: Install Chrome
      run: |
        sudo apt update
        sudo apt install -y wget unzip
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb

    - name: Remove old ChromeDriver
      run: sudo rm -f /usr/bin/chromedriver /usr/local/bin/chromedriver || true

        - name: Install matching ChromeDriver
      run: |
        set -e
        # Get full Chrome version (e.g., 130.0.6723.91)
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
        echo "Detected Chrome version: $CHROME_VERSION"

        # Get the latest compatible ChromeDriver version from Google Chrome Labs
        DRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_${CHROME_VERSION%%.*}")
        echo "Matching ChromeDriver version: $DRIVER_VERSION"

        # Download from the new official endpoint
        wget -N "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${DRIVER_VERSION}/linux64/chromedriver-linux64.zip" -O chromedriver_linux64.zip

        unzip -o chromedriver_linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Check Chrome version
      run: google-chrome --version

    - name: Check ChromeDriver version
      run: chromedriver --version

    - name: Run attendance script
      env:
        HONO_USERNAME: ${{ secrets.HONO_USERNAME }}
        HONO_PASSWORD: ${{ secrets.HONO_PASSWORD }}
      run: dotnet run --project AttendanceBot
