name: Daily Attendance

on:
  schedule:
    - cron: '30 5 * * *'   # 11:00 AM IST
    - cron: '30 15 * * *'  # 9:00 PM IST
  workflow_dispatch:

jobs:
  run-attendance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Install dependencies
      run: dotnet restore AttendanceBot

    - name: Install Chrome
      run: |
        sudo apt update
        sudo apt install -y wget unzip
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb

    - name: Run attendance script
      env:
        HONO_USERNAME: ${{ secrets.HONO_USERNAME }}
        HONO_PASSWORD: ${{ secrets.HONO_PASSWORD }}
      run: dotnet run --project AttendanceBot
